---

- name: Create Traefik provider
  ansible.builtin.template:
    src: provider.yml.j2
    dest: /home/{{ ansible_user }}/docker/traefik/traefik-data/providers/generated.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    # validate: "docker run --rm -v %s:/file aciobanu/dnsmasq --test -C /file"
