---

- name: Create Traefik provider
  ansible.builtin.template:
    src: provider.yml.j2
    dest: /home/{{ ansible_user }}/docker/traefik/traefik-data/providers/generated.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    # validate: "docker run --rm -v %s:/tmp/traefik.yml ghcr.io/otto-de/traefik-config-validator:v0.0.2 -cfg /tmp/traefik.yml"
  notify: Restart the traefik container
