---
- name: Configure Git
  hosts:
    # - supervisor
    - docker
  vars:
    editor: vim
    disable_logging: false
    only_show_keys: false
    git:
      color.ui: auto
      core.editor: "{{ editor }}"
      init.defaultBranch: main
      push.autoSetupRemote: true
      user.email: dev@charlie.fyi
      user.name: CJ
  tasks:

    - name: Ensure Git is installed
      become: true
      ansible.builtin.apt:
        name: git
        state: present

    - name: Ensure Git Editor is installed ("{{ editor }}")
      become: true
      ansible.builtin.apt:
        name: "{{ editor }}"
        state: present

    - name: Ensure Git is up to date
      become: true
      ansible.builtin.apt:
        name: git
        state: present
        only_upgrade: true

    - name: Configure Git config options
      community.general.git_config:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        scope: "global"
        state: present
      loop: "{{ git | dict2items }}"
      no_log: "{{ disable_logging | default(false) }}"
