---
- name: Configure Git
  hosts: supervisor
  vars:
    git_user_name: CJ
    git_user_email: dev@charlie.fyi
    git_default_branch: main
    git_editor: vim
  tasks:

    - name: Ensure Git is installed
      become: true
      ansible.builtin.apt:
        name: git
        state: present

    - name: Ensure Git Editor is installed ("{{ git_editor }}")
      become: true
      ansible.builtin.apt:
        name: "{{ git_editor }}"
        state: present

    - name: Ensure Git is up to date
      become: true
      ansible.builtin.apt:
        name: git
        state: present
        only_upgrade: true

    - name: Enable colorful output
      community.general.git_config:
        name: color.ui
        value: auto
        state: present

    - name: Ensure Git editor is `{{ git_editor }}`
      community.general.git_config:
        name: core.editor
        value: "{{ git_editor }}"
        scope: global
        state: present

    - name: Ensure Git username is `{{ git_user_name }}`
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_user_name }}"
        state: present

    - name: Ensure Git email is `{{ git_user_email }}`
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_user_email }}"
        state: present

    - name: Ensure Git default branch is `{{ git_default_branch }}`
      community.general.git_config:
        name: init.defaultBranch
        value: "{{ git_default_branch }}"
        scope: global
        state: present

