---
- name: Python
  hosts: supervisor
  pre_tasks:

    - name: Install ZSH
      ansible.builtin.apt:
        name:
          - python3
          - sense-hat
        update_cache: true
      become: true

    - name: Enable i2c
      ansible.builtin.shell: sudo raspi-config nonint do_i2c 0
      become: true

    - name: Install SenseHat Python library
      ansible.builtin.shell: sudo pip3 install sense-hat
      become: true

    - name: Copy SenseHat service
      ansible.builtin.copy:
        src: sensehat/sensehat.service
        dest: /etc/systemd/system/sensehat.service
        owner: root
        group: root
        mode: 0644
      become: true

    - name: Enable SenseHat service
      ansible.builtin.shell: sudo systemctl enable sensehat.service
      become: true

    - name: Start SenseHat service
      ansible.builtin.shell: sudo systemctl start sensehat.service
      become: true
