---

all:
  # Hosts
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: supervisor
    laptop:
      ansible_host: laptop.host.charj.dev
      ansible_user: charj
  children:
    # Guests
    guests:
      hosts:
        docker:
          ansible_host: docker.lab.charj.dev
          ansible_user: docker
        # goodleaf:
        #   ansible_host: 88.218.205.4
        #   ansible_user: root
    # Groups
    docker_hosts:
      hosts:
        localhost:
        docker:

    dns_servers:
      hosts:
        localhost:
        docker:

    idracs:
      hosts:
        alpha:
          ansible_host: idrac.alpha.lab.charj.dev
        bravo:
          ansible_host: idrac.bravo.lab.charj.dev
