---

dnsmasq:
  servers:
    - name: primary
      address: 10.10.0.10
    - name: secondary
      address: 10.0.0.2
  nameservers:
    - 1.0.0.1
    - 1.1.1.1
  options:
    - log-queries
    - no-resolv
    - no-poll
    - strict-order
  search: lab.charj.dev
  addresses:
    - name: supervisor.local
      address: "{{ ips.supervisor }}"
    - name: udm.lab.charj.dev
      address: "{{ ips.udm }}"
    - name: vcsa.lab.charj.dev
      address: "{{ ips.vcsa }}"
    - name: esxi.local
      address: "{{ ips.esxi.alpha }}"
    - name: truenas.local
      address: "{{ ips.truenas }}"
    - name: idrac.local
      address: "{{ ips.idrac.alpha }}"
    - name: supervisor.local
      address: "{{ ips.supervisor }}"
    - name: laptop.local
      address: "{{ ips.seeg.laptop }}"
    - name: printer.local
      address: "{{ ips.printer}}"
    - name: media.local
      address: "{{ ips.media }}"
    - name: dns1.local
      address: "{{ ips.dns.primary }}"
    - name: dns2.local
      address: "{{ ips.dns.secondary }}"
    - name: docker.local
      address: "{{ ips.docker }}"
    - name: lab.charj.dev
      address: "{{ ips.docker}}"
