---

- name: Ensure Git is installed
  become: true
  ansible.builtin.apt:
    name: git
    state: present

- name: Ensure Git Editor is installed ("{{ editor }}")
  become: true
  ansible.builtin.apt:
    name: "{{ editor }}"
    state: present

- name: Ensure Git is up to date
  become: true
  ansible.builtin.apt:
    name: git
    state: present
    only_upgrade: true
