---

- name: Create dnsmasq.conf
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /home/{{ ansible_user }}/docker/dnsmasq/dnsmasq.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    validate: "docker run --rm -v %s:/file aciobanu/dnsmasq --test -C /file"
  notify: Restart the dnsmasq container
