traefik:
  debug: true
  routers:

    # Docker Services
    - homarr:
      hostname: home.lab.charj.dev
      service: homarr
      url: http://docker.lab.charj.dev:7575
      # url: {{ url.homarr }}

    - traefik:
      hostname: traefik.lab.charj.dev
      service: traefik
      url: http://docker.lab.charj.dev:8080

    - uptime-kuma:
      hostname: uptime.lab.charj.dev
      service: uptime-kuma
      url: http://docker.lab.charj.dev:3001

    - portainer:
      hostname: portainer.lab.charj.dev
      service: portainer
      url: http://docker.lab.charj.dev:9000

    - prometheus:
      hostname: prometheus.lab.charj.dev
      service: prometheus
      url: http://docker.lab.charj.dev:9090

    - grafana:
      hostname: grafana.lab.charj.dev
      service: grafana
      url: http://docker.lab.charj.dev:3000

    # Management
    - vault:
      hostname: vault.lab.charj.dev
      service: vault
      url: https://supervisor.host.charj.dev:8200

    - udm:
      hostname: udm.lab.charj.dev
      service: udm
      url: "https://192.168.1.1"

    - truenas:
      hostname: truenas.lab.charj.dev
      service: truenas
      url: "http://10.0.0.21"

    # Media
    - overseerr:
      hostname: overseerr.lab.charj.dev
      service: overseerr
      url: http://streaming.host.charj.dev:5055

    - sonarr:
      hostname: sonarr.lab.charj.dev
      service: sonarr
      url: http://streaming.host.charj.dev:8989

    - prowlarr:
      hostname: prowlarr.lab.charj.dev
      service: prowlarr
      url: http://streaming.host.charj.dev:9696

    - radarr:
      hostname: radarr.lab.charj.dev
      service: radarr
      url: http://streaming.host.charj.dev:7878

    - qbittorrent:
      hostname: qbittorrent.lab.charj.dev
      service: qbittorrent
      url: http://streaming.host.charj.dev:8585

    - sabnzbd:
      hostname: sabnzbd.lab.charj.dev
      service: sabnzbd
      url: http://streaming.host.charj.dev:8686

    - tautulli:
      hostname: tautulli.lab.charj.dev
      service: tautulli
      url: http://streaming.host.charj.dev:8181

    - plex:
      hostname: plex.lab.charj.dev
      service: plex
      url: https://streaming.host.charj.dev:32400

    - deemix:
      hostname: deemix.lab.charj.dev
      service: deemix
      url: http://docker.lab.charj.dev:6595

    # Misc
    - printer:
      hostname: printer.lab.charj.dev
      service: printer
      url: http://printer.host.charj.dev

    - homeassistant:
      hostname: homeassistant.lab.charj.dev
      service: homeassistant
      url: http://homeassistant.host.charj.dev:8123

    # DNS
    - dns-primary:
      hostname: primary.dns.lab.charj.dev
      service: dns-1
      url: http://docker.lab.charj.dev:8053

    - dns-secondary:
      hostname: secondary.dns.lab.charj.dev
      service: dns-2
      url: http://supervisor.lab.charj.dev:8053
